services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  project-core:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - db

  magnetic-reed-listener:
    build: ./microservices/magnetic-reed-listener
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  db-data: