x-common-variables: &common-variables
   PG_CREDENTIALS_FILE: /shared/pg_credentials.json

services:
  db:
    image: postgres:16.4
    environment: *common-variables
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./database_init.sh:/usr/bin/database_init.sh
    expose:
      - "5432"
    command: ["/bin/bash", "/usr/bin/database_init.sh"]
    restart: on-failure

  project-core:
    build: .
    environment: *common-variables
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - shared:/shared
    restart: on-failure

  magnetic-reeds-listener:
    build: microservices/magnetic_reed_listener
    environment: *common-variables
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - shared:/shared
    restart: on-failure

volumes:
  db-data:
  shared:
